# Generated by Django 3.1.4 on 2022-04-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='stripe_card_last4',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='stripe_payment_method_id',
        ),
    ]
