# Generated by Django 3.1.4 on 2022-04-27 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.courier'),
        ),
    ]
