"""
Django settings for major project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fb-h#zj_u7d_spmj3k0ti8fj+rcis0(0&1vjzsj15kmp*bh3c_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'core',
    'core.apps.CoreConfig',
    'bootstrap5',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.ProfileMiddleware'
]

ROOT_URLCONF = 'major.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'major.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
LOGIN_URL = '/sign-in'
LOGIN_REDIRECT_URL = '/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = 'Crowd Source <no-reply@crowdSourced.localhost>'

FIREBASE_ADMIN_CREDENTIAL = os.path.join(BASE_DIR,"crowdsourced-del-firebase-adminsdk-u1wup-626252dbd2.json")

STRIPE_API_PUBLIC_KEY = "pk_test_51Kt3bASCgT2EgJVqzbUUu0Iuj6M9ofZx0GMdOKLVPs9O0uaEZmZJqrzWm8xl5mPgIU4QlWflRxuFQTgfnXrSz8Wr003PUS182x"
STRIPE_API_SECRET_KEY = "sk_test_51Kt3bASCgT2EgJVqSXO6F3Uex4p6R6N9FoT4APVOn9FwtXo62U7lwB7dwXcAlb91m4vrugRloFdRxMaLDByPKxO900Gbq9D6SS"

GOOGLE_MAP_API_KEY = "AIzaSyDz57vYS5YvYRK09PSOf4BildwK06HYHVk"
PAYPAL_MODE = "sandbox"
PAYPAL_CLIENT_ID = "AVJ98rT_DLhjqbVnyh6UAKUQ08GT4zZ_hqyIYLE5hkzlTJWpqleSosc1VXbTKQuW3jd_lC3uHkj-zuSe"
PAYPAL_CLIENT_SECRET = "EJdP-vTuZavitcWuskgRRVIP6OKckhvymnaKRsuaX88Sse0mBZRmFEdql0I3OP2gz-S6NAMluraZEs3y"

NOTIFICATION_URL = "https://crowdsourceddelivery.herokuapp.com/"
ASGI_APPLICATION = "major.asgi.application"

import django_on_heroku
django_on_heroku.settings(locals())
